package com.jeantuffier.statemachine.orchestrate

/**
 * The interface used as top level parent for the classes generated by ksp that represent an event.
 */
interface Event

/**
 * The parent interface required for action classes associated with a property of type
 * [com.jeantuffier.statemachine.orchestrate.OrchestratedPage]. It guarentees the action class has the offset and limit
 * properties.
 */
interface Pagination {
    val offset: Offset
    val limit: Limit
}
